package com.ded.thetitans;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@Mod.EventBusSubscriber(modid = "thetitans")
public class SoundRegistry {
    public static final SoundEvent FUNNY_EXPLOSION = new SoundEvent(new ResourceLocation("thetitans", "funny.explosion")).setRegistryName("funny.explosion");
    public static final SoundEvent EVILGOLEM_PUNCH = new SoundEvent(new ResourceLocation("thetitans", "evilgolem.punch")).setRegistryName("evilgolem.punch");
    public static final SoundEvent BIGZOMBIE_LIVING = new SoundEvent(new ResourceLocation("thetitans", "bigzombie.living")).setRegistryName("bigzombie.living");
    public static final SoundEvent BIGZOMBIE_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "bigzombie.grunt")).setRegistryName("bigzombie.grunt");
    public static final SoundEvent BIGZOMBIE_DEATH = new SoundEvent(new ResourceLocation("thetitans", "bigzombie.death")).setRegistryName("bigzombie.death");
    public static final SoundEvent GHOUL_LIVING = new SoundEvent(new ResourceLocation("thetitans", "ghoul.living")).setRegistryName("ghoul.living");
    public static final SoundEvent GHOUL_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "ghoul.grunt")).setRegistryName("ghoul.grunt");
    public static final SoundEvent GHOUL_DEATH = new SoundEvent(new ResourceLocation("thetitans", "ghoul.death")).setRegistryName("ghoul.death");
    public static final SoundEvent WIGHT_LIVING = new SoundEvent(new ResourceLocation("thetitans", "wight.living")).setRegistryName("wight.living");
    public static final SoundEvent WIGHT_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "wight.grunt")).setRegistryName("wight.grunt");
    public static final SoundEvent WIGHT_DEATH = new SoundEvent(new ResourceLocation("thetitans", "wight.death")).setRegistryName("wight.death");
    public static final SoundEvent WARLOCK_IDLE = new SoundEvent(new ResourceLocation("thetitans", "warlock.idle")).setRegistryName("warlock.idle");
    public static final SoundEvent WARLOCK_HURT = new SoundEvent(new ResourceLocation("thetitans", "warlock.hurt")).setRegistryName("warlock.hurt");
    public static final SoundEvent WRAITH_HURT = new SoundEvent(new ResourceLocation("thetitans", "wraith.hurt")).setRegistryName("wraith.hurt");
    public static final SoundEvent WRAITH_DEATH = new SoundEvent(new ResourceLocation("thetitans", "wraith.death")).setRegistryName("wraith.death");
    public static final SoundEvent CAST = new SoundEvent(new ResourceLocation("thetitans", "cast")).setRegistryName("cast");
    public static final SoundEvent CAST_ATTACK = new SoundEvent(new ResourceLocation("thetitans", "cast.attack")).setRegistryName("cast.attack");
    public static final SoundEvent CAST_PASSIVE = new SoundEvent(new ResourceLocation("thetitans", "cast.passive")).setRegistryName("cast.passive");
    public static final SoundEvent GARGOYLE_LIVING = new SoundEvent(new ResourceLocation("thetitans", "gargoyle.living")).setRegistryName("gargoyle.living");
    public static final SoundEvent GARGOYLE_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "gargoyle.grunt")).setRegistryName("gargoyle.grunt");
    public static final SoundEvent GARGOYLE_DEATH = new SoundEvent(new ResourceLocation("thetitans", "gargoyle.death")).setRegistryName("gargoyle.death");
    public static final SoundEvent TITAN_CRUSH_WOOD = new SoundEvent(new ResourceLocation("thetitans", "titan.crush.wood")).setRegistryName("titan.crush.wood");
    public static final SoundEvent TITAN_HIT_METAL = new SoundEvent(new ResourceLocation("thetitans", "titan.hit.metal")).setRegistryName("titan.hit.metal");
    public static final SoundEvent TITAN_PRESS = new SoundEvent(new ResourceLocation("thetitans", "titan.press")).setRegistryName("titan.press");
    public static final SoundEvent SWORD_DRAG = new SoundEvent(new ResourceLocation("thetitans", "sword.drag")).setRegistryName("sword.drag");
    public static final SoundEvent TITAN_SWING = new SoundEvent(new ResourceLocation("thetitans", "titan.swing")).setRegistryName("titan.swing");
    public static final SoundEvent SLASH_FLESH = new SoundEvent(new ResourceLocation("thetitans", "slash.flesh")).setRegistryName("slash.flesh");
    public static final SoundEvent DIMENSIONAL_TRANSPORT = new SoundEvent(new ResourceLocation("thetitans", "dimensional.transport")).setRegistryName("dimensional.transport");
    public static final SoundEvent HARCADIUM_HUM = new SoundEvent(new ResourceLocation("thetitans", "harcadium.hum")).setRegistryName("harcadium.hum");
    public static final SoundEvent HARCADIUM_BLOCK_HUM = new SoundEvent(new ResourceLocation("thetitans", "harcadium.block.hum")).setRegistryName("harcadium.block.hum");
    public static final SoundEvent LARGE_FALL = new SoundEvent(new ResourceLocation("thetitans", "large.fall")).setRegistryName("large.fall");
    public static final SoundEvent QUICK_APPERANCE = new SoundEvent(new ResourceLocation("thetitans", "quick.apperence")).setRegistryName("quick.apperence");
    public static final SoundEvent TITAN_BIRTH = new SoundEvent(new ResourceLocation("thetitans", "titan.birth")).setRegistryName("titan.birth");
    public static final SoundEvent TITAN_QUAKE = new SoundEvent(new ResourceLocation("thetitans", "titan.quake")).setRegistryName("titan.quake");
    public static final SoundEvent TITAN_RUMBLE = new SoundEvent(new ResourceLocation("thetitans", "titan.rumble")).setRegistryName("titan.rumble");
    public static final SoundEvent DISTANT_LARGE_FALL = new SoundEvent(new ResourceLocation("thetitans", "distant.large.fall")).setRegistryName("distant.large.fall");
    public static final SoundEvent TITAN_FALL = new SoundEvent(new ResourceLocation("thetitans", "titan.fall")).setRegistryName("titan.fall");
    public static final SoundEvent TITAN_SLAM = new SoundEvent(new ResourceLocation("thetitans", "titan.slam")).setRegistryName("titan.slam");
    public static final SoundEvent TITAN_STRIKE = new SoundEvent(new ResourceLocation("thetitans", "titan.strike")).setRegistryName("titan.strike");
    public static final SoundEvent GROUNDSMASH = new SoundEvent(new ResourceLocation("thetitans", "groundsmash")).setRegistryName("groundsmash");
    public static final SoundEvent OMG = new SoundEvent(new ResourceLocation("thetitans", "omg")).setRegistryName("omg");
    public static final SoundEvent CHAFF_DEPLOYMENT = new SoundEvent(new ResourceLocation("thetitans", "chaff.deployment")).setRegistryName("chaff.deployment");
    public static final SoundEvent TITAN_PUNCH = new SoundEvent(new ResourceLocation("thetitans", "titan.punch")).setRegistryName("titan.punch");
    public static final SoundEvent TITAN_LAND = new SoundEvent(new ResourceLocation("thetitans", "titan.land")).setRegistryName("titan.land");
    public static final SoundEvent TURRET_SHOOT = new SoundEvent(new ResourceLocation("thetitans", "turret.shoot")).setRegistryName("turret.shoot");
    public static final SoundEvent TURRET_DEATH = new SoundEvent(new ResourceLocation("thetitans", "turret.death")).setRegistryName("turret.death");
    public static final SoundEvent TURRET_SHOOT_2 = new SoundEvent(new ResourceLocation("thetitans", "turret.shoot.2")).setRegistryName("turret.shoot.2");
    public static final SoundEvent TURRET_DEATH_2 = new SoundEvent(new ResourceLocation("thetitans", "turret.death.2")).setRegistryName("turret.death.2");
    public static final SoundEvent MORTAR_SHOOT = new SoundEvent(new ResourceLocation("thetitans", "mortar.shoot")).setRegistryName("mortar.shoot");
    public static final SoundEvent MORTAR_HIT = new SoundEvent(new ResourceLocation("thetitans", "mortar.hit")).setRegistryName("mortar.hit");
    public static final SoundEvent TURRET_DEATH_3 = new SoundEvent(new ResourceLocation("thetitans", "turret.death.3")).setRegistryName("turret.death.3");
    public static final SoundEvent TITAN_SUMMON_MINION = new SoundEvent(new ResourceLocation("thetitans", "titan.summon.minion")).setRegistryName("titan.summon.minion");
    public static final SoundEvent PREDATOR_SPIDER = new SoundEvent(new ResourceLocation("thetitans", "predator.spider")).setRegistryName("predator.spider");
    public static final SoundEvent LIGHTNING_THROW = new SoundEvent(new ResourceLocation("thetitans", "lightning.throw")).setRegistryName("lightning.throw");
    public static final SoundEvent LIGHTNING_CHARGE = new SoundEvent(new ResourceLocation("thetitans", "lightning.charge")).setRegistryName("lightning.charge");
    public static final SoundEvent TITAN_ZOMBIE_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.zombie.living")).setRegistryName("titan.zombie.living");
    public static final SoundEvent TITAN_ZOMBIE_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.zombie.grunt")).setRegistryName("titan.zombie.grunt");
    public static final SoundEvent TITAN_STEP = new SoundEvent(new ResourceLocation("thetitans", "titan.step")).setRegistryName("titan.step");
    public static final SoundEvent TITAN_ZOMBIE_ROAR = new SoundEvent(new ResourceLocation("thetitans", "titan.zombie.roar")).setRegistryName("titan.zombie.roar");
    public static final SoundEvent TITAN_ZOMBIE_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.zombie.death")).setRegistryName("titan.zombie.death");
    public static final SoundEvent TITAN_ZOMBIE_CREATION = new SoundEvent(new ResourceLocation("thetitans", "titan.zombie.creation")).setRegistryName("titan.zombie.creation");
    public static final SoundEvent TITAN_SPIDER_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.spider.living")).setRegistryName("titan.spider.living");
    public static final SoundEvent TITAN_SPIDER_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.spider.grunt")).setRegistryName("titan.spider.grunt");
    public static final SoundEvent TITAN_SPIDER_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.spider.death")).setRegistryName("titan.spider.death");
    public static final SoundEvent TITAN_CREEPER_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.living")).setRegistryName("titan.creeper.living");
    public static final SoundEvent TITAN_CREEPER_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.grunt")).setRegistryName("titan.creeper.grunt");
    public static final SoundEvent TITAN_CREEPER_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.death")).setRegistryName("titan.creeper.death");
    public static final SoundEvent TITAN_CREEPER_STUN = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.stun")).setRegistryName("titan.creeper.stun");
    public static final SoundEvent TITAN_CREEPER_WARNING = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.warning")).setRegistryName("titan.creeper.warning");
    public static final SoundEvent TITAN_CREEPER_EXPLOSION = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.explosion")).setRegistryName("titan.creeper.explosion");
    public static final SoundEvent TITAN_CREEPER_AWAKEN = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.awaken")).setRegistryName("titan.creeper.awaken");
    public static final SoundEvent TITAN_CREEPER_BEGINMOVE = new SoundEvent(new ResourceLocation("thetitans", "titan.creeper.beginmove")).setRegistryName("titan.creeper.beginmove");
    public static final SoundEvent TITAN_GHAST_FIREBALL = new SoundEvent(new ResourceLocation("thetitans", "titan.ghast.fireball")).setRegistryName("titan.ghast.fireball");
    public static final SoundEvent TITAN_GHAST_CHARGE = new SoundEvent(new ResourceLocation("thetitans", "titan.ghast.charge")).setRegistryName("titan.ghast.charge");
    public static final SoundEvent TITAN_GHAST_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.ghast.living")).setRegistryName("titan.ghast.living");
    public static final SoundEvent TITAN_GHAST_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.ghast.grunt")).setRegistryName("titan.ghast.grunt");
    public static final SoundEvent TITAN_GHAST_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.ghast.death")).setRegistryName("titan.ghast.death");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_SCREAM = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.scream")).setRegistryName("titan.endercolossus.scream");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_SCREAMLONG = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.screamlong")).setRegistryName("titan.endercolossus.screamlong");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_CHOMP = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.chomp")).setRegistryName("titan.endercolossus.chomp");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_STARE = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.stare")).setRegistryName("titan.endercolossus.stare");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_ROAR = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.roar")).setRegistryName("titan.endercolossus.roar");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.living")).setRegistryName("titan.endercolossus.living");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.grunt")).setRegistryName("titan.endercolossus.grunt");
    public static final SoundEvent TITAN_ENDERCOLOSSUS_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.endercolossus.death")).setRegistryName("titan.endercolossus.death");
    public static final SoundEvent TITAN_PIGZOMBIE_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.pigzombie.living")).setRegistryName("titan.pigzombie.living");
    public static final SoundEvent TITAN_PIGZOMBIE_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.pigzombie.grunt")).setRegistryName("titan.pigzombie.grunt");
    public static final SoundEvent TITAN_PIGZOMBIE_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.pigzombie.death")).setRegistryName("titan.pigzombie.death");
    public static final SoundEvent TITAN_BLAZE_BREATHE = new SoundEvent(new ResourceLocation("thetitans", "titan.blaze.breathe")).setRegistryName("titan.blaze.breathe");
    public static final SoundEvent TITAN_BLAZE_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.blaze.grunt")).setRegistryName("titan.blaze.grunt");
    public static final SoundEvent TITAN_BLAZE_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.blaze.death")).setRegistryName("titan.blaze.death");
    public static final SoundEvent TITAN_SILVERFISH_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.silverfish.living")).setRegistryName("titan.silverfish.living");
    public static final SoundEvent TITAN_SILVERFISH_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.silverfish.grunt")).setRegistryName("titan.silverfish.grunt");
    public static final SoundEvent TITAN_SILVERFISH_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.silverfish.death")).setRegistryName("titan.silverfish.death");
    public static final SoundEvent TITAN_SKELETON_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.living")).setRegistryName("titan.skeleton.living");
    public static final SoundEvent TITAN_SKELETON_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.grunt")).setRegistryName("titan.skeleton.grunt");
    public static final SoundEvent TITAN_SKELETON_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.death")).setRegistryName("titan.skeleton.death");
    public static final SoundEvent TITAN_WITHERSKELETON_LIVING = new SoundEvent(new ResourceLocation("thetitans", "titan.witherskeleton.living")).setRegistryName("titan.witherskeleton.living");
    public static final SoundEvent TITAN_WITHERSKELETON_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "titan.witherskeleton.grunt")).setRegistryName("titan.witherskeleton.grunt");
    public static final SoundEvent TITAN_WITHERSKELETON_DEATH = new SoundEvent(new ResourceLocation("thetitans", "titan.witherskeleton.death")).setRegistryName("titan.witherskeleton.death");
    public static final SoundEvent TITAN_SKELETON_AWAKEN = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.awaken")).setRegistryName("titan.skeleton.awaken");
    public static final SoundEvent TITAN_SKELETON_BEGINMOVE = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.beginmove")).setRegistryName("titan.skeleton.beginmove");
    public static final SoundEvent TITAN_SKELETON_GETUP = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.getup")).setRegistryName("titan.skeleton.getup");
    public static final SoundEvent TITAN_SKELETON_BONECRUNCH = new SoundEvent(new ResourceLocation("thetitans", "titan.skeleton.bonecrunch")).setRegistryName("titan.skeleton.bonecrunch");
    public static final SoundEvent WITHERZILLA_LIVING = new SoundEvent(new ResourceLocation("thetitans", "witherzilla.living")).setRegistryName("witherzilla.living");
    public static final SoundEvent WITHERZILLA_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "witherzilla.grunt")).setRegistryName("witherzilla.grunt");
    public static final SoundEvent WITHERZILLA_SPAWN = new SoundEvent(new ResourceLocation("thetitans", "witherzilla.spawn")).setRegistryName("witherzilla.spawn");
    public static final SoundEvent WITHERZILLA_DEATH = new SoundEvent(new ResourceLocation("thetitans", "witherzilla.death")).setRegistryName("witherzilla.death");
    public static final SoundEvent EXECUTOR_DRAGON_LIVING = new SoundEvent(new ResourceLocation("thetitans", "executor.dragon.living")).setRegistryName("executor.dragon.living");
    public static final SoundEvent EXECUTOR_DRAGON_GRUNT = new SoundEvent(new ResourceLocation("thetitans", "executor.dragon.grunt")).setRegistryName("executor.dragon.grunt");
    public static final SoundEvent EXECUTOR_DRAGON_DEATH = new SoundEvent(new ResourceLocation("thetitans", "executor.dragon.death")).setRegistryName("executor.dragon.death");
    public static final SoundEvent EXECUTOR_DRAGON_FLAP = new SoundEvent(new ResourceLocation("thetitans", "executor.dragon.flap")).setRegistryName("executor.dragon.flap");

    @SubscribeEvent
    public static void registerSounds(RegistryEvent.Register<SoundEvent> event) {
        // Register all sound events
        event.getRegistry().register(WITHERZILLA_SPAWN);
        event.getRegistry().register(FUNNY_EXPLOSION);
        event.getRegistry().register(EVILGOLEM_PUNCH);
        event.getRegistry().register(BIGZOMBIE_LIVING);
        event.getRegistry().register(BIGZOMBIE_GRUNT);
        event.getRegistry().register(BIGZOMBIE_DEATH);
        event.getRegistry().register(GHOUL_LIVING);
        event.getRegistry().register(GHOUL_GRUNT);
        event.getRegistry().register(GHOUL_DEATH);
        event.getRegistry().register(WIGHT_LIVING);
        event.getRegistry().register(WIGHT_GRUNT);
        event.getRegistry().register(WIGHT_DEATH);
        event.getRegistry().register(WARLOCK_IDLE);
        event.getRegistry().register(WARLOCK_HURT);
        event.getRegistry().register(WRAITH_HURT);
        event.getRegistry().register(WRAITH_DEATH);
        event.getRegistry().register(CAST);
        event.getRegistry().register(CAST_ATTACK);
        event.getRegistry().register(CAST_PASSIVE);
        event.getRegistry().register(GARGOYLE_LIVING);
        event.getRegistry().register(GARGOYLE_GRUNT);
        event.getRegistry().register(GARGOYLE_DEATH);
        event.getRegistry().register(TITAN_CRUSH_WOOD);
        event.getRegistry().register(TITAN_HIT_METAL);
        event.getRegistry().register(TITAN_PRESS);
        event.getRegistry().register(SWORD_DRAG);
        event.getRegistry().register(TITAN_SWING);
        event.getRegistry().register(SLASH_FLESH);
        event.getRegistry().register(DIMENSIONAL_TRANSPORT);
        event.getRegistry().register(HARCADIUM_HUM);
        event.getRegistry().register(HARCADIUM_BLOCK_HUM);
        event.getRegistry().register(LARGE_FALL);
        event.getRegistry().register(QUICK_APPERANCE);
        event.getRegistry().register(TITAN_BIRTH);
        event.getRegistry().register(TITAN_QUAKE);
        event.getRegistry().register(TITAN_RUMBLE);
        event.getRegistry().register(DISTANT_LARGE_FALL);
        event.getRegistry().register(TITAN_FALL);
        event.getRegistry().register(TITAN_SLAM);
        event.getRegistry().register(TITAN_STRIKE);
        event.getRegistry().register(GROUNDSMASH);
        event.getRegistry().register(OMG);
        event.getRegistry().register(CHAFF_DEPLOYMENT);
        event.getRegistry().register(TITAN_PUNCH);
        event.getRegistry().register(TITAN_LAND);
        event.getRegistry().register(TURRET_SHOOT);
        event.getRegistry().register(TURRET_DEATH);
        event.getRegistry().register(TURRET_SHOOT_2);
        event.getRegistry().register(TURRET_DEATH_2);
        event.getRegistry().register(MORTAR_SHOOT);
        event.getRegistry().register(MORTAR_HIT);
        event.getRegistry().register(TURRET_DEATH_3);
        event.getRegistry().register(TITAN_SUMMON_MINION);
        event.getRegistry().register(PREDATOR_SPIDER);
        event.getRegistry().register(LIGHTNING_THROW);
        event.getRegistry().register(LIGHTNING_CHARGE);
        event.getRegistry().register(TITAN_ZOMBIE_LIVING);
        event.getRegistry().register(TITAN_ZOMBIE_GRUNT);
        event.getRegistry().register(TITAN_STEP);
        event.getRegistry().register(TITAN_ZOMBIE_ROAR);
        event.getRegistry().register(TITAN_ZOMBIE_DEATH);
        event.getRegistry().register(TITAN_ZOMBIE_CREATION);
        event.getRegistry().register(TITAN_SPIDER_LIVING);
        event.getRegistry().register(TITAN_SPIDER_GRUNT);
        event.getRegistry().register(TITAN_SPIDER_DEATH);
        event.getRegistry().register(TITAN_CREEPER_LIVING);
        event.getRegistry().register(TITAN_CREEPER_GRUNT);
        event.getRegistry().register(TITAN_CREEPER_DEATH);
        event.getRegistry().register(TITAN_CREEPER_STUN);
        event.getRegistry().register(TITAN_CREEPER_WARNING);
        event.getRegistry().register(TITAN_CREEPER_EXPLOSION);
        event.getRegistry().register(TITAN_CREEPER_AWAKEN);
        event.getRegistry().register(TITAN_CREEPER_BEGINMOVE);
        event.getRegistry().register(TITAN_GHAST_FIREBALL);
        event.getRegistry().register(TITAN_GHAST_CHARGE);
        event.getRegistry().register(TITAN_GHAST_LIVING);
        event.getRegistry().register(TITAN_GHAST_GRUNT);
        event.getRegistry().register(TITAN_GHAST_DEATH);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_SCREAM);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_SCREAMLONG);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_CHOMP);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_STARE);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_ROAR);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_LIVING);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_GRUNT);
        event.getRegistry().register(TITAN_ENDERCOLOSSUS_DEATH);
        event.getRegistry().register(TITAN_PIGZOMBIE_LIVING);
        event.getRegistry().register(TITAN_PIGZOMBIE_GRUNT);
        event.getRegistry().register(TITAN_PIGZOMBIE_DEATH);
        event.getRegistry().register(TITAN_BLAZE_BREATHE);
        event.getRegistry().register(TITAN_BLAZE_GRUNT);
        event.getRegistry().register(TITAN_BLAZE_DEATH);
        event.getRegistry().register(TITAN_SILVERFISH_LIVING);
        event.getRegistry().register(TITAN_SILVERFISH_GRUNT);
        event.getRegistry().register(TITAN_SILVERFISH_DEATH);
        event.getRegistry().register(TITAN_SKELETON_LIVING);
        event.getRegistry().register(TITAN_SKELETON_GRUNT);
        event.getRegistry().register(TITAN_SKELETON_DEATH);
        event.getRegistry().register(TITAN_WITHERSKELETON_LIVING);
        event.getRegistry().register(TITAN_WITHERSKELETON_GRUNT);
        event.getRegistry().register(TITAN_WITHERSKELETON_DEATH);
        event.getRegistry().register(TITAN_SKELETON_AWAKEN);
        event.getRegistry().register(TITAN_SKELETON_BEGINMOVE);
        event.getRegistry().register(TITAN_SKELETON_GETUP);
        event.getRegistry().register(TITAN_SKELETON_BONECRUNCH);
        event.getRegistry().register(WITHERZILLA_LIVING);
        event.getRegistry().register(WITHERZILLA_GRUNT);
        event.getRegistry().register(WITHERZILLA_DEATH);
        event.getRegistry().register(EXECUTOR_DRAGON_LIVING);
        event.getRegistry().register(EXECUTOR_DRAGON_GRUNT);
        event.getRegistry().register(EXECUTOR_DRAGON_DEATH);
        event.getRegistry().register(EXECUTOR_DRAGON_FLAP);
    }
}