package com.ded.thetitans;

import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraft.util.ResourceLocation;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static com.ded.thetitans.Tags.MODID;

@Mod.EventBusSubscriber(modid = MODID)
public class SoundEvents {
    private static final Logger LOGGER = LogManager.getLogger("TheTitans|Sound");

    // Sound events from sounds.json
    public static SoundEvent FUNNY_EXPLOSION;
    public static SoundEvent EVIL_GOLEM_PUNCH;
    public static SoundEvent BIG_ZOMBIE_LIVING;
    public static SoundEvent BIG_ZOMBIE_GRUNT;
    public static SoundEvent BIG_ZOMBIE_DEATH;
    public static SoundEvent GHOUL_LIVING;
    public static SoundEvent GHOUL_GRUNT;
    public static SoundEvent GHOUL_DEATH;
    public static SoundEvent WIGHT_LIVING;
    public static SoundEvent WIGHT_GRUNT;
    public static SoundEvent WIGHT_DEATH;
    public static SoundEvent WARLOCK_IDLE;
    public static SoundEvent WARLOCK_HURT;
    public static SoundEvent WRAITH_HURT;
    public static SoundEvent WRAITH_DEATH;
    public static SoundEvent CAST;
    public static SoundEvent CAST_ATTACK;
    public static SoundEvent CAST_PASSIVE;
    public static SoundEvent GARGOYLE_LIVING;
    public static SoundEvent GARGOYLE_GRUNT;
    public static SoundEvent GARGOYLE_DEATH;
    public static SoundEvent TITAN_CRUSH_WOOD;
    public static SoundEvent TITAN_HIT_METAL;
    public static SoundEvent TITAN_PRESS;
    public static SoundEvent SWORD_DRAG;
    public static SoundEvent TITAN_SWING;
    public static SoundEvent SLASH_FLESH;
    public static SoundEvent DIMENSIONAL_TRANSPORT;
    public static SoundEvent HARCADIUM_HUM;
    public static SoundEvent HARCADIUM_BLOCK_HUM;
    public static SoundEvent LARGE_FALL;
    public static SoundEvent QUICK_APPERANCE;
    public static SoundEvent TITAN_BIRTH;
    public static SoundEvent TITAN_QUAKE;
    public static SoundEvent TITAN_RUMBLE;
    public static SoundEvent DISTANT_LARGE_FALL;
    public static SoundEvent TITAN_FALL;
    public static SoundEvent TITAN_SLAM;
    public static SoundEvent TITAN_STRIKE;
    public static SoundEvent GROUND_SMASH;
    public static SoundEvent OMG;
    public static SoundEvent CHAFF_DEPLOYMENT;
    public static SoundEvent TITAN_PUNCH;
    public static SoundEvent TITAN_LAND;
    public static SoundEvent TURRET_SHOOT;
    public static SoundEvent TURRET_DEATH;
    public static SoundEvent TURRET_SHOOT_2;
    public static SoundEvent TURRET_DEATH_2;
    public static SoundEvent MORTAR_SHOOT;
    public static SoundEvent MORTAR_HIT;
    public static SoundEvent TURRET_DEATH_3;
    public static SoundEvent TITAN_SUMMON_MINION;
    public static SoundEvent PREDATOR_SPIDER;
    public static SoundEvent LIGHTNING_THROW;
    public static SoundEvent LIGHTNING_CHARGE;
    public static SoundEvent ZOMBT_LIVING;
    public static SoundEvent ZOMBT_GRUNT;
    public static SoundEvent TITAN_STEP;
    public static SoundEvent ZOMBT_ROAR;
    public static SoundEvent ZOMBT_DEATH;
    public static SoundEvent ZOMBT_CREATION;
    public static SoundEvent TITAN_SPIDER_LIVING;
    public static SoundEvent TITAN_SPIDER_GRUNT;
    public static SoundEvent TITAN_SPIDER_DEATH;
    public static SoundEvent TITAN_CREEPER_LIVING;
    public static SoundEvent TITAN_CREEPER_GRUNT;
    public static SoundEvent TITAN_CREEPER_DEATH;
    public static SoundEvent TITAN_CREEPER_STUN;
    public static SoundEvent TITAN_CREEPER_WARNING;
    public static SoundEvent TITAN_CREEPER_EXPLOSION;
    public static SoundEvent TITAN_CREEPER_AWAKEN;
    public static SoundEvent TITAN_CREEPER_BEGINMOVE;
    public static SoundEvent TITAN_GHAST_FIREBALL;
    public static SoundEvent TITAN_GHAST_CHARGE;
    public static SoundEvent TITAN_GHAST_LIVING;
    public static SoundEvent TITAN_GHAST_GRUNT;
    public static SoundEvent TITAN_GHAST_DEATH;
    public static SoundEvent TITAN_ENDERCOLOSSUS_SCREAM;
    public static SoundEvent TITAN_ENDERCOLOSSUS_SCREAM_LONG;
    public static SoundEvent CHOMP;
    public static SoundEvent TITAN_ENDERCOLOSSUS_STARE;
    public static SoundEvent TITAN_ENDERCOLOSSUS_ROAR;
    public static SoundEvent TITAN_ENDERCOLOSSUS_LIVING;
    public static SoundEvent TITAN_ENDERCOLOSSUS_GRUNT;
    public static SoundEvent TITAN_ENDERCOLOSSUS_DEATH;
    public static SoundEvent TITAN_PIGZOMBIE_LIVING;
    public static SoundEvent TITAN_PIGZOMBIE_GRUNT;
    public static SoundEvent TITAN_PIGZOMBIE_DEATH;
    public static SoundEvent TITAN_BLAZE_BREATHE;
    public static SoundEvent TITAN_BLAZE_GRUNT;
    public static SoundEvent TITAN_BLAZE_DEATH;
    public static SoundEvent TITAN_SILVERFISH_LIVING;
    public static SoundEvent TITAN_SILVERFISH_GRUNT;
    public static SoundEvent TITAN_SILVERFISH_DEATH;
    public static SoundEvent TITAN_SKELETON_LIVING;
    public static SoundEvent TITAN_SKELETON_GRUNT;
    public static SoundEvent TITAN_SKELETON_DEATH;
    public static SoundEvent TITAN_WITHERSKELETON_LIVING;
    public static SoundEvent TITAN_WITHERSKELETON_GRUNT;
    public static SoundEvent TITAN_WITHERSKELETON_DEATH;
    public static SoundEvent TITAN_SKELETON_AWAKEN;
    public static SoundEvent TITAN_SKELETON_BEGINMOVE;
    public static SoundEvent TITAN_SKELETON_GETUP;
    public static SoundEvent TITAN_SKELETON_BONECRUNCH;
    public static SoundEvent WITHERZILLA_SPAWN;
    public static SoundEvent WITHERZILLA_LIVING;
    public static SoundEvent WITHERZILLA_GRUNT;
    public static SoundEvent WITHERZILLA_DEATH;
    public static SoundEvent EXECUTOR_DRAGON_LIVING;
    public static SoundEvent EXECUTOR_DRAGON_GRUNT;
    public static SoundEvent EXECUTOR_DRAGON_DEATH;
    public static SoundEvent EXECUTOR_DRAGON_FLAP;

    @SubscribeEvent
    public static void registerSounds(RegistryEvent.Register<SoundEvent> event) {
        LOGGER.info("Manually registering all sound events from sounds.json");
        
        FUNNY_EXPLOSION = createSoundEvent("funny.explosion");
        EVIL_GOLEM_PUNCH = createSoundEvent("evilgolem.punch");
        BIG_ZOMBIE_LIVING = createSoundEvent("bigzombie.living");
        BIG_ZOMBIE_GRUNT = createSoundEvent("bigzombie.grunt");
        BIG_ZOMBIE_DEATH = createSoundEvent("bigzombie.death");
        GHOUL_LIVING = createSoundEvent("ghoul.living");
        GHOUL_GRUNT = createSoundEvent("ghoul.grunt");
        GHOUL_DEATH = createSoundEvent("ghoul.death");
        WIGHT_LIVING = createSoundEvent("wight.living");
        WIGHT_GRUNT = createSoundEvent("wight.grunt");
        WIGHT_DEATH = createSoundEvent("wight.death");
        WARLOCK_IDLE = createSoundEvent("warlock.idle");
        WARLOCK_HURT = createSoundEvent("warlock.hurt");
        WRAITH_HURT = createSoundEvent("wraith.hurt");
        WRAITH_DEATH = createSoundEvent("wraith.death");
        CAST = createSoundEvent("cast");
        CAST_ATTACK = createSoundEvent("cast.attack");
        CAST_PASSIVE = createSoundEvent("cast.passive");
        GARGOYLE_LIVING = createSoundEvent("gargoyle.living");
        GARGOYLE_GRUNT = createSoundEvent("gargoyle.grunt");
        GARGOYLE_DEATH = createSoundEvent("gargoyle.death");
        TITAN_CRUSH_WOOD = createSoundEvent("titan.crush.wood");
        TITAN_HIT_METAL = createSoundEvent("titan.hit.metal");
        TITAN_PRESS = createSoundEvent("titan.press");
        SWORD_DRAG = createSoundEvent("sword.drag");
        TITAN_SWING = createSoundEvent("titan.swing");
        SLASH_FLESH = createSoundEvent("slash.flesh");
        DIMENSIONAL_TRANSPORT = createSoundEvent("dimensional.transport");
        HARCADIUM_HUM = createSoundEvent("harcadium.hum");
        HARCADIUM_BLOCK_HUM = createSoundEvent("harcadium.block.hum");
        LARGE_FALL = createSoundEvent("large.fall");
        QUICK_APPERANCE = createSoundEvent("quick.apperence");
        TITAN_BIRTH = createSoundEvent("titan.birth");
        TITAN_QUAKE = createSoundEvent("titan.quake");
        TITAN_RUMBLE = createSoundEvent("titan.rumble");
        DISTANT_LARGE_FALL = createSoundEvent("distant.large.fall");
        TITAN_FALL = createSoundEvent("titan.fall");
        TITAN_SLAM = createSoundEvent("titan.slam");
        TITAN_STRIKE = createSoundEvent("titan.strike");
        GROUND_SMASH = createSoundEvent("groundsmash");
        OMG = createSoundEvent("omg");
        CHAFF_DEPLOYMENT = createSoundEvent("chaff.deployment");
        TITAN_PUNCH = createSoundEvent("titan.punch");
        TITAN_LAND = createSoundEvent("titan.land");
        TURRET_SHOOT = createSoundEvent("turret.shoot");
        TURRET_DEATH = createSoundEvent("turret.death");
        TURRET_SHOOT_2 = createSoundEvent("turret.shoot.2");
        TURRET_DEATH_2 = createSoundEvent("turret.death.2");
        MORTAR_SHOOT = createSoundEvent("mortar.shoot");
        MORTAR_HIT = createSoundEvent("mortar.hit");
        TURRET_DEATH_3 = createSoundEvent("turret.death.3");
        TITAN_SUMMON_MINION = createSoundEvent("titan.summon.minion");
        PREDATOR_SPIDER = createSoundEvent("predator.spider");
        LIGHTNING_THROW = createSoundEvent("lightning.throw");
        LIGHTNING_CHARGE = createSoundEvent("lightning.charge");
        ZOMBT_LIVING = createSoundEvent("titan.zombie.living");
        ZOMBT_GRUNT = createSoundEvent("titan.zombie.grunt");
        TITAN_STEP = createSoundEvent("titan.step");
        ZOMBT_ROAR = createSoundEvent("titan.zombie.roar");
        ZOMBT_DEATH = createSoundEvent("titan.zombie.death");
        ZOMBT_CREATION = createSoundEvent("titan.zombie.creation");
        TITAN_SPIDER_LIVING = createSoundEvent("titan.spider.living");
        TITAN_SPIDER_GRUNT = createSoundEvent("titan.spider.grunt");
        TITAN_SPIDER_DEATH = createSoundEvent("titan.spider.death");
        TITAN_CREEPER_LIVING = createSoundEvent("titan.creeper.living");
        TITAN_CREEPER_GRUNT = createSoundEvent("titan.creeper.grunt");
        TITAN_CREEPER_DEATH = createSoundEvent("titan.creeper.death");
        TITAN_CREEPER_STUN = createSoundEvent("titan.creeper.stun");
        TITAN_CREEPER_WARNING = createSoundEvent("titan.creeper.warning");
        TITAN_CREEPER_EXPLOSION = createSoundEvent("titan.creeper.explosion");
        TITAN_CREEPER_AWAKEN = createSoundEvent("titan.creeper.awaken");
        TITAN_CREEPER_BEGINMOVE = createSoundEvent("titan.creeper.beginmove");
        TITAN_GHAST_FIREBALL = createSoundEvent("titan.ghast.fireball");
        TITAN_GHAST_CHARGE = createSoundEvent("titan.ghast.charge");
        TITAN_GHAST_LIVING = createSoundEvent("titan.ghast.living");
        TITAN_GHAST_GRUNT = createSoundEvent("titan.ghast.grunt");
        TITAN_GHAST_DEATH = createSoundEvent("titan.ghast.death");
        TITAN_ENDERCOLOSSUS_SCREAM = createSoundEvent("titan.endercolossus.scream");
        TITAN_ENDERCOLOSSUS_SCREAM_LONG = createSoundEvent("titan.endercolossus.screamlong");
        CHOMP = createSoundEvent("titan.endercolossus.chomp");
        TITAN_ENDERCOLOSSUS_STARE = createSoundEvent("titan.endercolossus.stare");
        TITAN_ENDERCOLOSSUS_ROAR = createSoundEvent("titan.endercolossus.roar");
        TITAN_ENDERCOLOSSUS_LIVING = createSoundEvent("titan.endercolossus.living");
        TITAN_ENDERCOLOSSUS_GRUNT = createSoundEvent("titan.endercolossus.grunt");
        TITAN_ENDERCOLOSSUS_DEATH = createSoundEvent("titan.endercolossus.death");
        TITAN_PIGZOMBIE_LIVING = createSoundEvent("titan.pigzombie.living");
        TITAN_PIGZOMBIE_GRUNT = createSoundEvent("titan.pigzombie.grunt");
        TITAN_PIGZOMBIE_DEATH = createSoundEvent("titan.pigzombie.death");
        TITAN_BLAZE_BREATHE = createSoundEvent("titan.blaze.breathe");
        TITAN_BLAZE_GRUNT = createSoundEvent("titan.blaze.grunt");
        TITAN_BLAZE_DEATH = createSoundEvent("titan.blaze.death");
        TITAN_SILVERFISH_LIVING = createSoundEvent("titan.silverfish.living");
        TITAN_SILVERFISH_GRUNT = createSoundEvent("titan.silverfish.grunt");
        TITAN_SILVERFISH_DEATH = createSoundEvent("titan.silverfish.death");
        TITAN_SKELETON_LIVING = createSoundEvent("titan.skeleton.living");
        TITAN_SKELETON_GRUNT = createSoundEvent("titan.skeleton.grunt");
        TITAN_SKELETON_DEATH = createSoundEvent("titan.skeleton.death");
        TITAN_WITHERSKELETON_LIVING = createSoundEvent("titan.witherskeleton.living");
        TITAN_WITHERSKELETON_GRUNT = createSoundEvent("titan.witherskeleton.grunt");
        TITAN_WITHERSKELETON_DEATH = createSoundEvent("titan.witherskeleton.death");
        TITAN_SKELETON_AWAKEN = createSoundEvent("titan.skeleton.awaken");
        TITAN_SKELETON_BEGINMOVE = createSoundEvent("titan.skeleton.beginmove");
        TITAN_SKELETON_GETUP = createSoundEvent("titan.skeleton.getup");
        TITAN_SKELETON_BONECRUNCH = createSoundEvent("titan.skeleton.bonecrunch");
        WITHERZILLA_SPAWN = createSoundEvent("witherzilla.spawn");
        WITHERZILLA_LIVING = createSoundEvent("witherzilla.living");
        WITHERZILLA_GRUNT = createSoundEvent("witherzilla.grunt");
        WITHERZILLA_DEATH = createSoundEvent("witherzilla.death");
        EXECUTOR_DRAGON_LIVING = createSoundEvent("executor.dragon.living");
        EXECUTOR_DRAGON_GRUNT = createSoundEvent("executor.dragon.grunt");
        EXECUTOR_DRAGON_DEATH = createSoundEvent("executor.dragon.death");
        EXECUTOR_DRAGON_FLAP = createSoundEvent("executor.dragon.flap");
        
        // Register all sound events
        registerSoundEvent(event, FUNNY_EXPLOSION);
        registerSoundEvent(event, EVIL_GOLEM_PUNCH);
        registerSoundEvent(event, BIG_ZOMBIE_LIVING);
        registerSoundEvent(event, BIG_ZOMBIE_GRUNT);
        registerSoundEvent(event, BIG_ZOMBIE_DEATH);
        registerSoundEvent(event, GHOUL_LIVING);
        registerSoundEvent(event, GHOUL_GRUNT);
        registerSoundEvent(event, GHOUL_DEATH);
        registerSoundEvent(event, WIGHT_LIVING);
        registerSoundEvent(event, WIGHT_GRUNT);
        registerSoundEvent(event, WIGHT_DEATH);
        registerSoundEvent(event, WARLOCK_IDLE);
        registerSoundEvent(event, WARLOCK_HURT);
        registerSoundEvent(event, WRAITH_HURT);
        registerSoundEvent(event, WRAITH_DEATH);
        registerSoundEvent(event, CAST);
        registerSoundEvent(event, CAST_ATTACK);
        registerSoundEvent(event, CAST_PASSIVE);
        registerSoundEvent(event, GARGOYLE_LIVING);
        registerSoundEvent(event, GARGOYLE_GRUNT);
        registerSoundEvent(event, GARGOYLE_DEATH);
        registerSoundEvent(event, TITAN_CRUSH_WOOD);
        registerSoundEvent(event, TITAN_HIT_METAL);
        registerSoundEvent(event, TITAN_PRESS);
        registerSoundEvent(event, SWORD_DRAG);
        registerSoundEvent(event, TITAN_SWING);
        registerSoundEvent(event, SLASH_FLESH);
        registerSoundEvent(event, DIMENSIONAL_TRANSPORT);
        registerSoundEvent(event, HARCADIUM_HUM);
        registerSoundEvent(event, HARCADIUM_BLOCK_HUM);
        registerSoundEvent(event, LARGE_FALL);
        registerSoundEvent(event, QUICK_APPERANCE);
        registerSoundEvent(event, TITAN_BIRTH);
        registerSoundEvent(event, TITAN_QUAKE);
        registerSoundEvent(event, TITAN_RUMBLE);
        registerSoundEvent(event, DISTANT_LARGE_FALL);
        registerSoundEvent(event, TITAN_FALL);
        registerSoundEvent(event, TITAN_SLAM);
        registerSoundEvent(event, TITAN_STRIKE);
        registerSoundEvent(event, GROUND_SMASH);
        registerSoundEvent(event, OMG);
        registerSoundEvent(event, CHAFF_DEPLOYMENT);
        registerSoundEvent(event, TITAN_PUNCH);
        registerSoundEvent(event, TITAN_LAND);
        registerSoundEvent(event, TURRET_SHOOT);
        registerSoundEvent(event, TURRET_DEATH);
        registerSoundEvent(event, TURRET_SHOOT_2);
        registerSoundEvent(event, TURRET_DEATH_2);
        registerSoundEvent(event, MORTAR_SHOOT);
        registerSoundEvent(event, MORTAR_HIT);
        registerSoundEvent(event, TURRET_DEATH_3);
        registerSoundEvent(event, TITAN_SUMMON_MINION);
        registerSoundEvent(event, PREDATOR_SPIDER);
        registerSoundEvent(event, LIGHTNING_THROW);
        registerSoundEvent(event, LIGHTNING_CHARGE);
        registerSoundEvent(event, ZOMBT_LIVING);
        registerSoundEvent(event, ZOMBT_GRUNT);
        registerSoundEvent(event, TITAN_STEP);
        registerSoundEvent(event, ZOMBT_ROAR);
        registerSoundEvent(event, ZOMBT_DEATH);
        registerSoundEvent(event, ZOMBT_CREATION);
        registerSoundEvent(event, TITAN_SPIDER_LIVING);
        registerSoundEvent(event, TITAN_SPIDER_GRUNT);
        registerSoundEvent(event, TITAN_SPIDER_DEATH);
        registerSoundEvent(event, TITAN_CREEPER_LIVING);
        registerSoundEvent(event, TITAN_CREEPER_GRUNT);
        registerSoundEvent(event, TITAN_CREEPER_DEATH);
        registerSoundEvent(event, TITAN_CREEPER_STUN);
        registerSoundEvent(event, TITAN_CREEPER_WARNING);
        registerSoundEvent(event, TITAN_CREEPER_EXPLOSION);
        registerSoundEvent(event, TITAN_CREEPER_AWAKEN);
        registerSoundEvent(event, TITAN_CREEPER_BEGINMOVE);
        registerSoundEvent(event, TITAN_GHAST_FIREBALL);
        registerSoundEvent(event, TITAN_GHAST_CHARGE);
        registerSoundEvent(event, TITAN_GHAST_LIVING);
        registerSoundEvent(event, TITAN_GHAST_GRUNT);
        registerSoundEvent(event, TITAN_GHAST_DEATH);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_SCREAM);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_SCREAM_LONG);
        registerSoundEvent(event, CHOMP);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_STARE);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_ROAR);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_LIVING);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_GRUNT);
        registerSoundEvent(event, TITAN_ENDERCOLOSSUS_DEATH);
        registerSoundEvent(event, TITAN_PIGZOMBIE_LIVING);
        registerSoundEvent(event, TITAN_PIGZOMBIE_GRUNT);
        registerSoundEvent(event, TITAN_PIGZOMBIE_DEATH);
        registerSoundEvent(event, TITAN_BLAZE_BREATHE);
        registerSoundEvent(event, TITAN_BLAZE_GRUNT);
        registerSoundEvent(event, TITAN_BLAZE_DEATH);
        registerSoundEvent(event, TITAN_SILVERFISH_LIVING);
        registerSoundEvent(event, TITAN_SILVERFISH_GRUNT);
        registerSoundEvent(event, TITAN_SILVERFISH_DEATH);
        registerSoundEvent(event, TITAN_SKELETON_LIVING);
        registerSoundEvent(event, TITAN_SKELETON_GRUNT);
        registerSoundEvent(event, TITAN_SKELETON_DEATH);
        registerSoundEvent(event, TITAN_WITHERSKELETON_LIVING);
        registerSoundEvent(event, TITAN_WITHERSKELETON_GRUNT);
        registerSoundEvent(event, TITAN_WITHERSKELETON_DEATH);
        registerSoundEvent(event, TITAN_SKELETON_AWAKEN);
        registerSoundEvent(event, TITAN_SKELETON_BEGINMOVE);
        registerSoundEvent(event, TITAN_SKELETON_GETUP);
        registerSoundEvent(event, TITAN_SKELETON_BONECRUNCH);
        registerSoundEvent(event, WITHERZILLA_SPAWN);
        registerSoundEvent(event, WITHERZILLA_LIVING);
        registerSoundEvent(event, WITHERZILLA_GRUNT);
        registerSoundEvent(event, WITHERZILLA_DEATH);
        registerSoundEvent(event, EXECUTOR_DRAGON_LIVING);
        registerSoundEvent(event, EXECUTOR_DRAGON_GRUNT);
        registerSoundEvent(event, EXECUTOR_DRAGON_DEATH);
        registerSoundEvent(event, EXECUTOR_DRAGON_FLAP);
        
        LOGGER.info("Registered all sound events from sounds.json");
    }

    private static SoundEvent createSoundEvent(String name) {
        ResourceLocation location = new ResourceLocation(MODID, name);
        return new SoundEvent(location).setRegistryName(location);
    }

    private static void registerSoundEvent(RegistryEvent.Register<SoundEvent> event, SoundEvent soundEvent) {
        if (soundEvent != null) {
            event.getRegistry().register(soundEvent);
            LOGGER.info("Registered sound event: {}", soundEvent.getRegistryName());
        } else {
            LOGGER.error("Failed to register null sound event");
        }
    }
}